spring:
  application:
    name: advanced-hibernate-java26
  datasource:
    url: jdbc:h2:mem:advanced-hibernate;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        default_batch_fetch_size: 32
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.stat: debug
