spring:
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: false
          region.factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
        jakarta:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
